/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#define CYCLES_PER_MS 16000
#define CTRL_ENABLE (1U<<0)
#define CTRL_CLKSRC (1U<<2)
#define CTRL_COUNTFLAG (1u<<16)

void systickDelayMS(int delay){
	// The unit of delay is ms. So the idea is that we should we make a for loop, that counts the number times COUNTFLAG is set to 1. Each cycle of the loop counts exactly 1ms.
	// Repeat till we reach the delay desired. 

	// Reload value is the number of clock cycles per milisec. 
	// Recall that if each period has N processor clock cycles, RELOAD value should be N-1
	SysTick->LOAD = CYCLES_PER_MS - 1 ;

	// Clear systick current value register
	SysTick->VAL = 0;

	// Enable systick and select internal clk src
	SysTick->CTRL = CTRL_ENABLE | CTRL_CLKSRC;

	for(int i = 0; i < delay; i++){
		// This empty loop waits until countflag is set
		while((SysTick->CTRL & CTRL_COUNTFLAG) == 0){}
	}

	// Finished delaying. Writing 0 to CTRL registers means disabling the timer
	SysTick->CTRL = 0;
}

int main(void)
{
    //ENABLE GPIOB
	RCC->AHB1ENR |= (1U<<1); 

    /* SET PIN 5 AS OUTPUT */
    GPIOB->MODER |= (1U<<10);
	GPIOB->MODER &= ~(1U<11);

	while(1){
		GPIOB->ODR ^= (1U<<5); // TOGGLE PIN 5
		systickDelayMS(1000);
	}
}