/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

int main(void)
{
    //ENABLE GPIOB
	RCC->AHB1ENR |= (1U<<1); 

    /* SET PIN 5 AS OUTPUT */
    GPIOB->MODER |= (1U<<10);
	GPIOB->MODER &= ~(1U<11);

	while(1){
		GPIOB->ODR ^= (1U<<5); // TOGGLE PIN 5
		for(int i = 0; i < 1E6; i++){}	
	}
}

